# Generated by Django 3.1.14 on 2023-12-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20231210_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(choices=[('Mumbai', 'Mumbai'), ('Bangalore', 'Bangalore'), ('Pune', 'Pune'), ('Remote', 'Remote'), ('Johannesburg', 'Johannesburg'), ('Cape Town', 'Cape Town'), ('Durban', 'Durban'), ('Pretoria', 'Pretoria'), ('Port Elizabeth', 'Port Elizabeth'), ('Bloemfontein', 'Bloemfontein'), ('Polokwane', 'Polokwane'), ('Nelspruit', 'Nelspruit'), ('Kimberley', 'Kimberley')], max_length=50),
        ),
    ]
